services:
  - type: web
    name: hope-health
    env: static
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_GEMINI_API_KEY
        sync: false
      - key: VITE_GOOGLE_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html